repos:
  - repo: local
    hooks:
      - id: make-clean
        name: Make Clean
        entry: bash -c 'cd c && make clean'
        language: system
        files: ^c/
        pass_filenames: false
